---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/gmussyco/public_html/DEX
    - /bin/cp -R build/static $DEPLOYPATH
    - /bin/cp -R build/static/css $DEPLOYPATH
    - /bin/cp -R build/static/js $DEPLOYPATH
    - /bin/cp -R build/static/media $DEPLOYPATH
    - /bin/cp build/*.* $DEPLOYPATH
    - /bin/cp src/logo.png $DEPLOYPATH
